# AI文档测试系统 - Docker部署配置
# 用户只需要配置此文件中的关键信息即可一键部署

# 应用基础配置
app:
  name: "aidd"                    # 应用名称，用于容器命名
  version: "2.0.0"                # 应用版本

# 服务端口配置
ports:
  frontend: 3000                  # 前端访问端口
  backend: 8080                   # 后端API端口
  
# 数据库配置
database:
  type: "postgresql"              # 数据库类型: sqlite/mysql/postgresql
  # SQLite配置（如果选择sqlite则只需要这个）
  sqlite:
    path: "./data/app.db"
  # MySQL配置（如果选择mysql）
  mysql:
    host: "mysql"
    port: 3306
    database: "aidd_db"
    username: "aidd"
    password: "change_me_mysql_password"  # 请修改为安全密码
    root_password: "change_me_root_password"  # MySQL root密码
  # PostgreSQL配置（如果选择postgresql）
  postgresql:
    host: "postgres"
    port: 5432
    database: "aidd_db"
    username: "aidd"
    password: "change_me_pg_password"     # 请修改为安全密码

# Redis缓存配置
redis:
  host: "redis"
  port: 6379
  password: ""                    # Redis密码（可选）
  database: 0

# 外部访问配置
external:
  protocol: "http"                # 协议: http/https
  host: "localhost"               # 外部访问域名或IP
  backend_port: 8080              # 后端外部端口
  frontend_port: 3000             # 前端外部端口

# AI服务配置
ai_services:
  openai:
    api_key: "your-openai-api-key-here"      # OpenAI API密钥
    base_url: "https://api.openai.com/v1"    # API基础URL
  baidu:
    api_key: "your-baidu-api-key-here"       # 百度AI API密钥
  deepseek:
    api_key: "your-deepseek-api-key-here"    # DeepSeek API密钥

# 第三方登录配置
oauth:
  provider: "gitee"               # 登录提供商: gitee/github
  client_id: "your-oauth-client-id"         # OAuth应用ID
  client_secret: "your-oauth-client-secret" # OAuth应用密钥
  scope: "user_info"              # 权限范围

# 安全配置
security:
  jwt_secret: "change_me_jwt_secret_key"    # JWT密钥，请修改为安全的随机字符串
  oauth_secret: "change_me_oauth_secret"    # OAuth密钥

# 环境配置
environment:
  mode: "production"              # 运行模式: development/production
  debug: false                    # 调试模式
  log_level: "INFO"               # 日志级别: DEBUG/INFO/WARNING/ERROR

# 文件存储配置
storage:
  max_file_size: "10MB"           # 最大上传文件大小
  upload_dir: "/app/data/uploads" # 上传目录
  report_dir: "/app/data/reports" # 报告目录

# 任务处理配置
task_processing:
  max_concurrent_tasks: 10        # 最大并发任务数
  timeout: 1800                   # 任务超时时间（秒）
  retry_attempts: 3               # 最大重试次数