# 服务器配置
server:
  host: "${SERVER_HOST:0.0.0.0}"  # 监听地址
  port: "${SERVER_PORT:8080}"  # 监听端口
  debug: "${DEBUG:false}"  # 调试模式
  reload: "${RELOAD:false}"  # 自动重载
  workers: "${WORKERS:1}"  # 工作进程数
  # 外部访问地址配置
  external_host: "${EXTERNAL_HOST:localhost}"  # 外部访问主机名
  external_port: "${EXTERNAL_PORT:8080}"  # 外部访问端口
  external_protocol: "${EXTERNAL_PROTOCOL:http}"  # 外部访问协议

# 数据库配置
database:
  # 数据库类型: sqlite 或 mysql
  type: "sqlite"
  
  # SQLite配置（默认）
  sqlite:
    path: "./data/app.db"
  
  # MySQL配置（可选）
  mysql:
    host: "${MYSQL_HOST:localhost}"
    port: "${MYSQL_PORT:3306}"
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PASSWORD}"
    database: "${MYSQL_DATABASE:ai_doc_test}"
    charset: "utf8mb4"
    # 连接池配置
    pool:
      pool_size: 5
      max_overflow: 10
      pool_timeout: 30
      pool_recycle: 3600
      pool_pre_ping: true

# AI模型配置（保持现有结构）
ai_models:
  default_index: 0
  models:
    - label: "GPT-4o Mini (快速)"
      provider: "openai"
      config:
        api_key: "${OPENAI_API_KEY}"
        base_url: "https://api.openai.com/v1"
        model: "gpt-4o-mini"
        temperature: 0.3
        max_tokens: 8000
        context_window: 128000
        reserved_tokens: 2000
        timeout: 12000
        max_retries: 3
      description: "适合快速处理，成本较低"


# 文件设置  
file_settings:
  max_file_size: 10485760  # 10MB
  chunk_size: 4000  # 文本分块大小（废弃，改为从模型配置动态计算）
  allowed_extensions:
    - pdf
    - docx
    - md
    - txt

# 目录配置
directories:
  upload_dir: ./data/uploads
  report_dir: ./data/reports
  log_dir: ./data/logs
  temp_dir: ./data/temp

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./data/logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# 任务处理配置
task_processing:
  # 并发限制配置
  concurrency_limits:
    system_max_concurrent_tasks: 100  # 系统级最大并发任务数
    default_user_max_concurrent_tasks: 10  # 用户默认最大并发任务数
    admin_max_concurrent_tasks: 50  # 管理员默认最大并发任务数
    vip_max_concurrent_tasks: 20  # VIP用户最大并发任务数（预留）
    
  max_concurrent_tasks: 3  # 最大并发任务数（已废弃，保留兼容性）
  task_timeout: 12000  # 任务超时时间（秒）
  retry_failed_tasks: true  # 是否重试失败的任务
  
  # 大文档处理配置
  document_processing:
    max_document_chars: 1000000  # 允许处理的最大文档字符数（1M字符）
    enable_intelligent_chunking: true  # 启用智能分块处理
    chunk_overlap_chars: 200  # 分块重叠字符数
    min_chunk_chars: 20000  # 最小分批大小（20K字符，约5-8页PDF）
    max_chunks_per_document: 50  # 单个文档最大分块数量
    
    # 分批处理配置
    batch_size_small: 50000   # 小文档批次大小（50K字符，约10-15页PDF）
    batch_size_medium: 60000  # 中等文档批次大小（60K字符，约12-18页PDF） 
    batch_size_large: 80000   # 大文档批次大小（80K字符，约16-24页PDF）
    
    # 文档大小阈值（字符数）
    small_doc_threshold: 100000   # 小文档阈值（10万字符，约20页）
    large_doc_threshold: 200000   # 大文档阈值（20万字符，约40页）
  
  # 章节合并配置
  section_merge:
    enabled: true  # 是否启用章节合并
    max_chars: 15000  # 合并后章节最大字符数（约3000-4000 tokens，适合AI处理）
    min_chars: 500   # 最小章节字符数（短于此数值的章节总是被合并）
    preserve_structure: true  # 是否保持章节层级结构
  
# CORS配置
cors:
  enabled: true
  origins:
    - "${FRONTEND_URL_1:http://localhost:3000}"  # 主前端地址
    - "${FRONTEND_URL_2:http://localhost:3001}"  # 备用前端地址1
    - "${FRONTEND_URL_3:http://localhost:3002}"  # 备用前端地址2
    - "${FRONTEND_URL_4:http://localhost:3003}"  # 备用前端地址3
    - "${FRONTEND_URL_5:http://localhost:5173}"  # Vite开发服务器地址
    - "${FRONTEND_URL_6:http://127.0.0.1:3000}"  # 本地IP访问
    - "${FRONTEND_URL_7:http://127.0.0.1:5173}"  # 本地IP Vite访问
    # 生产环境前端地址
    - "${FRONTEND_PRODUCTION_URL:}"  # 生产环境前端地址
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]
  # 开发模式：允许更宽松的CORS策略
  development_mode: "${CORS_DEVELOPMENT_MODE:false}"  # 默认false，可通过环境变量启用


# 第三方登录配置
# Gitee OAuth真实配置
third_party_auth:
  # 提供商类型：使用Gitee
  provider_type: "gitee"
  
  # 实际的Gitee应用配置
  client_id: "077b1f29dbb4c4fda233c93ba34676b00421b2b16d11abc36b38f6298e495876"
  client_secret: "f3d0cfe1a3143a1b99ca58f234920f0ac63645e6272f65c5771a3a4e4f085fa4"
  
  # 回调配置 - 前端域名和路径
  frontend_domain: "${FRONTEND_DOMAIN:http://localhost:3000}"
  redirect_path: "${OAUTH_REDIRECT_PATH:/third-login/callback}"
  
  # Gitee权限范围
  scope: "user_info"
  
  # Gitee标准API端点（会自动设置，这里列出供参考）
  api_endpoints:
    authorization_url: "https://gitee.com/oauth/authorize"
    token_url: "https://gitee.com/oauth/token"
    userinfo_url: "https://gitee.com/api/v5/user"
  
  
  # 超时和重试配置
  request_timeout: 30  # 请求超时时间（秒）
  max_retries: 3  # 最大重试次数
  

# JWT配置
jwt:
  secret_key: "${JWT_SECRET_KEY}"  # 从环境变量获取
  algorithm: "HS256"
  access_token_expire_minutes: 30
  
# 环境变量映射（可选）
env_mapping:
  JWT_SECRET_KEY: "JWT_SECRET_KEY"