"""初始数据库架构：创建所有表

Revision ID: 0719bfc9e700
Revises: 
Create Date: 2025-08-29 13:28:52.024570

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0719bfc9e700'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('reserved_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_env', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_index(op.f('ix_ai_models_model_key'), 'ai_models', ['model_key'], unique=True)
    op.create_table('file_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('encoding', sa.String(length=50), nullable=True),
    sa.Column('document_chars', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.String(length=20), nullable=True),
    sa.Column('process_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_infos_content_hash'), 'file_infos', ['content_hash'], unique=False)
    op.create_index(op.f('ix_file_infos_id'), 'file_infos', ['id'], unique=False)
    op.create_table('queue_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index(op.f('ix_queue_config_id'), 'queue_config', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_system_admin', sa.Boolean(), nullable=True),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_infos.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_file_id'), 'tasks', ['file_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_model_id'), 'tasks', ['model_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_status_created_at', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index('ix_tasks_user_id_created_at', 'tasks', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_tasks_user_id_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_index('ix_tasks_user_id_status_created_at', 'tasks', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('ai_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('section_index', sa.Integer(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_outputs_id'), 'ai_outputs', ['id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('user_impact', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('satisfaction_rating', sa.Float(), nullable=True),
    sa.Column('feedback_user_id', sa.Integer(), nullable=True),
    sa.Column('feedback_user_name', sa.String(length=100), nullable=True),
    sa.Column('feedback_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['feedback_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_feedback_type'), 'issues', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_issues_feedback_user_id'), 'issues', ['feedback_user_id'], unique=False)
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_task_id'), 'issues', ['task_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.create_table('task_queue',
    sa.Column('id', sa.Integer(), nullable=False, comment='队列项ID'),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联任务ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级1-10，越大越优先'),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='queuestatus'), nullable=True, comment='队列状态'),
    sa.Column('worker_id', sa.String(length=50), nullable=True, comment='处理工作者ID'),
    sa.Column('queued_at', sa.DateTime(), nullable=True, comment='入队时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始处理时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('attempts', sa.Integer(), nullable=True, comment='已尝试次数'),
    sa.Column('max_attempts', sa.Integer(), nullable=True, comment='最大重试次数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('task_data', sa.JSON(), nullable=True, comment='任务数据快照'),
    sa.Column('estimated_duration', sa.Integer(), nullable=True, comment='预估处理时长(秒)'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_queue_id'), 'task_queue', ['id'], unique=False)
    op.create_table('task_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_user_id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=False),
    sa.Column('share_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_shares_unique', 'task_shares', ['task_id', 'shared_user_id'], unique=True)
    op.create_index(op.f('ix_task_shares_id'), 'task_shares', ['id'], unique=False)
    op.create_index(op.f('ix_task_shares_is_active'), 'task_shares', ['is_active'], unique=False)
    op.create_index(op.f('ix_task_shares_owner_id'), 'task_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_task_shares_shared_user_id'), 'task_shares', ['shared_user_id'], unique=False)
    op.create_index(op.f('ix_task_shares_task_id'), 'task_shares', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_shares_task_id'), table_name='task_shares')
    op.drop_index(op.f('ix_task_shares_shared_user_id'), table_name='task_shares')
    op.drop_index(op.f('ix_task_shares_owner_id'), table_name='task_shares')
    op.drop_index(op.f('ix_task_shares_is_active'), table_name='task_shares')
    op.drop_index(op.f('ix_task_shares_id'), table_name='task_shares')
    op.drop_index('idx_task_shares_unique', table_name='task_shares')
    op.drop_table('task_shares')
    op.drop_index(op.f('ix_task_queue_id'), table_name='task_queue')
    op.drop_table('task_queue')
    op.drop_index(op.f('ix_task_logs_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_issues_task_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_feedback_user_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_feedback_type'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_ai_outputs_id'), table_name='ai_outputs')
    op.drop_table('ai_outputs')
    op.drop_index('ix_tasks_user_id_status_created_at', table_name='tasks')
    op.drop_index('ix_tasks_user_id_status', table_name='tasks')
    op.drop_index('ix_tasks_user_id_created_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index('ix_tasks_status_created_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_model_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_file_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_queue_config_id'), table_name='queue_config')
    op.drop_table('queue_config')
    op.drop_index(op.f('ix_file_infos_id'), table_name='file_infos')
    op.drop_index(op.f('ix_file_infos_content_hash'), table_name='file_infos')
    op.drop_table('file_infos')
    op.drop_index(op.f('ix_ai_models_model_key'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_id'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###