"""修复模型字段与数据库表结构不匹配问题

Revision ID: 1ac494a8172f
Revises: b8785a7e3405
Create Date: 2025-08-29 12:53:59.367262

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ac494a8172f'
down_revision: Union[str, None] = 'b8785a7e3405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'test_migration_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('test_migration_field', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='临时测试字段用于验证Alembic迁移'))
    # ### end Alembic commands ###