name: Frontend Build Test

on:
  push:
    branches: [ main, develop ]
    paths: ['frontend/**', '.github/workflows/frontend-build-fix.yml']
  pull_request:
    branches: [ main ]
    paths: ['frontend/**', '.github/workflows/frontend-build-fix.yml']

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
        
    - name: Check TypeScript compilation
      run: npx tsc --noEmit
        
    - name: Build project
      run: npm run build
        
    - name: Verify build output
      run: |
        if [ -d "dist" ]; then
          echo "✓ Build successful - output directory created"
          ls -la dist/
        else
          echo "✗ Build failed - no output directory found"
          exit 1
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-output
        path: frontend/dist/
        retention-days: 7