name: Frontend Build Fix

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend-build-fix.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/frontend-build-fix.yml'

jobs:
  build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Verify environment
      run: |
        echo "Node.js: $(node --version)"
        echo "npm: $(npm --version)"
        echo "Working directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
    
    - name: Clean npm cache and install
      run: |
        npm cache clean --force
        npm ci --prefer-offline --no-audit --no-fund --timeout=300000
    
    - name: Verify critical packages
      run: |
        echo "Verifying key dependencies..."
        npm list typescript vite react react-dom @types/react --depth=0 || true
        
        echo "Checking TypeScript executable..."
        npx tsc --version || echo "TypeScript not found"
        
        echo "Checking Vite executable..."
        npx vite --version || echo "Vite not found"
    
    - name: TypeScript compilation check
      run: |
        echo "Running TypeScript compilation..."
        npx tsc --noEmit --incremental false --skipLibCheck
    
    - name: Build project
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
      run: |
        echo "Building project with increased memory..."
        npm run build
    
    - name: Verify build success
      run: |
        if [ -d "dist" ]; then
          echo "✅ Build successful!"
          echo "Build output:"
          ls -la dist/
          echo "Total size:"
          du -sh dist/
          
          # 检查关键文件
          if [ -f "dist/index.html" ]; then
            echo "✅ index.html exists"
          else
            echo "❌ index.html missing"
            exit 1
          fi
        else
          echo "❌ Build failed - no dist directory"
          exit 1
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: frontend-build-output
        path: frontend/dist/
        retention-days: 7